In [35]:
import pandas as pd

df1 = pd.read_csv('metrike/prompts/llm_stress_test_results.csv')
df2 = pd.read_csv('metrike/prompts/llm_chat_test_results.csv')
df3 = pd.read_csv('metrike/prompts/llm_summarize_test_results.csv')
df4 = pd.read_csv('metrike/prompts/llm_batch_test_results.csv')

df = pd.concat([df1, df2, df3, df4], ignore_index=True)

df.head(10)

,timestamp,test_name,prompt_index,model,prompt,ttft,tpot,tokens_per_sec,latency,num_tokens,status_code,prompt_tokens,output_tokens,assistant_output,summary_output,output_text
0,2025-07-24 13:59:16.695294,stress,0,deepseek,Identify the steps involved in creating an eff...,30.477675,0.219441,4.589821,30.502276,140.0,200.0,NaN,NaN,NaN,NaN,NaN
1,2025-07-24 14:05:04.549569,stress,0,gemma3,Identify the steps involved in creating an eff...,129.391173,0.944493,1.066498,129.395502,138.0,200.0,NaN,NaN,NaN,NaN,NaN
2,2025-07-24 14:12:04.768615,stress,0,mistral,Identify the steps involved in creating an eff...,3.353979,0.024161,41.686827,3.358375,140.0,200.0,NaN,NaN,NaN,NaN,NaN
3,2025-07-24 14:12:45.556953,stress,0,meta-llama,Identify the steps involved in creating an eff...,3.398621,0.024477,41.148974,3.402272,140.0,200.0,NaN,NaN,NaN,NaN,NaN
4,2025-07-24 13:59:44.131259,chat,0,deepseek,User: Compare and contrast a grammar checker a...,27.423831,0.193187,5.212774,27.432613,NaN,NaN,15.0,143.0,User: Compare and contrast a grammar checker a...,NaN,NaN
5,2025-07-24 14:07:44.380894,chat,0,gemma3,User: Compare and contrast a grammar checker a...,159.822007,1.125562,0.894702,159.829743,NaN,NaN,15.0,143.0,User: Compare and contrast a grammar checker a...,NaN,NaN
6,2025-07-24 14:12:08.116371,chat,0,mistral,User: Compare and contrast a grammar checker a...,3.337567,0.022763,44.229300,3.346198,NaN,NaN,20.0,148.0,User: Compare and contrast a grammar checker a...,NaN,NaN
7,2025-07-24 14:12:48.987671,chat,0,meta-llama,User: Compare and contrast a grammar checker a...,3.419229,0.024143,41.711088,3.428345,NaN,NaN,15.0,143.0,User: Compare and contrast a grammar checker a...,NaN,NaN
8,2025-07-24 14:00:15.821946,summarizer,0,deepseek,Summarize the following document in 1500 words...,31.626034,0.002571,388.935789,31.635042,12304.0,200.0,NaN,NaN,NaN,Summarize the following document in 1500 words...,NaN
9,2025-07-24 14:08:21.872046,summarizer,0,gemma3,Summarize the following document in 1500 words...,37.448045,0.003061,326.737654,37.455126,12238.0,200.0,NaN,NaN,NaN,Summarize the following document in 1500 words...,NaN

In [36]:
## Define the models of interest
models_to_analyze = ['gemma3', 'mistral', 'meta-llama']
test_names_to_analyze = ['stress', 'chat', 'summarizer', 'batch']
# Filter the DataFrame to only include the specified models
df_filtered_models = df[
    (df['model'].isin(models_to_analyze)) &
    (df['test_name'].isin(test_names_to_analyze))
]

# Group by model and calculate the desired statistics for the 'ttft' column
statistics = df_filtered_models.groupby('model')['ttft'].agg(
    median='median',
    p99=lambda x: x.quantile(0.99),
    average='mean',
    std_dev='std',
    min='min',
    max='max',
).reset_index()

statistics

,model,median,p99,average,std_dev,min,max
0,deepseek,5.042409,46.152909,20.263942,19.927430,3.962617,46.152909
1,gemma3,1.796406,139.737657,30.972146,38.298310,1.757218,159.822007
2,meta-llama,4.003860,4.095304,3.730026,0.376587,3.236016,4.095304
3,mistral,3.774472,4.020400,3.677538,0.260019,3.273864,4.020400

In [37]:
# Filter the DataFrame to only include the specified models
df_filtered_models = df[
    (df['model'].isin(models_to_analyze)) &
    (df['test_name'].isin(test_names_to_analyze))
]

# Group by model and calculate the desired statistics for the 'ttft' column
statistics = df_filtered_models.groupby('test_name')['ttft'].agg(
    median='median',
    p99=lambda x: x.quantile(0.99),
    average='mean',
    std_dev='std',
    min='min',
    max='max',
).reset_index()

statistics

,test_name,median,p99,average,std_dev,min,max
0,batch,3.970141,70.469781,13.638592,21.925518,1.757218,70.469781
1,chat,15.421530,155.850062,48.500659,75.074886,3.337567,159.822007
2,stress,16.938148,126.423768,41.655362,59.869545,3.353979,129.391173
3,summarizer,17.803498,37.273385,19.255257,17.805239,3.965984,37.448045

In [38]:
# Filter the DataFrame to only include the specified models
df_filtered_models = df[
    (df['model'].isin(models_to_analyze)) &
    (df['test_name'].isin(test_names_to_analyze))
]

# Group by model and calculate the desired statistics for the 'ttft' column
statistics = df_filtered_models.groupby('test_name')['tpot'].agg(
    median='median',
    p99=lambda x: x.quantile(0.99),
    average='mean',
    std_dev='std',
    min='min',
    max='max',
).reset_index()

statistics

    test_name    median       p99   average   std_dev       min       max
0       batch  0.027419  1.484384  0.117823  0.252787  0.010490  1.904759
1        chat  0.108665  1.097590  0.341414  0.528853  0.022763  1.125562
2      stress  0.121959  0.922741  0.303143  0.437349  0.024161  0.944493
3  summarizer  0.001453  0.003046  0.001562  0.001462  0.000282  0.003061